CREATE TABLE INICIATIVA_ESG (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR2(150) NOT NULL,
    CATEGORIA VARCHAR2(20) NOT NULL,
    RESPONSAVEL VARCHAR2(100) NOT NULL,
    META_REDUCAO_CO2 NUMBER(18,2),
    STATUS VARCHAR2(20) DEFAULT 'PLANEJADA'
);
